/*
 * gl_shaders.h — GPU 渲染管线 GLSL 源码
 * 噪声/Sobel/JFA 为 GPU 实现; 图层合成 shader 是预设引擎的 GPU 实现
 * (与 dissolve_styles 数学一致)。当前插件默认走 CPU 管线 (dissolve_direct),
 * 本文件保留 GPU 实现。
 */
#pragma once

// 全屏三角形顶点着色器 (与设计一致)
static const char* kVSFullscreen =
    "#version 330\n"
    "in vec4 vertex;\n"
    "in vec2 tex;\n"
    "out vec2 texCoord;\n"
    "void main() {\n"
    "    gl_Position = vertex;\n"
    "    texCoord = tex;\n"
    "}\n";

// ============ 噪声图: Simplex 3D FBM (旋转八度) ============
static const char* kNoiseFS =
    "#version 330\n"
    "out float FragColour;\n"
    "in vec2 texCoord;\n"
    "uniform float noiseScale;\n"
    "uniform float scaleX;\n"
    "uniform float scaleY;\n"
    "uniform float contrast;\n"
    "uniform float brightness;\n"
    "uniform float evolution;\n"
    "uniform float aspect;\n"
    "uniform float layerOffsetX;\n"
    "uniform float layerOffsetY;\n"
    "uniform float userOffsetX;\n"
    "uniform float userOffsetY;\n"
    "uniform int complexityL;\n"
    "uniform float ghettoContrast;\n"
    "vec3 mod289(vec3 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }\n"
    "vec4 mod289(vec4 x) { return x - floor(x * (1.0 / 289.0)) * 289.0; }\n"
    "vec4 permute(vec4 x) { return mod289(((x*34.0)+10.0)*x); }\n"
    "vec4 taylorInvSqrt(vec4 r) { return 1.79284291400159 - 0.85373472095314 * r; }\n"
    "float simplex3d(vec3 v) {\n"
    "  const vec2 C = vec2(1.0/6.0, 1.0/3.0);\n"
    "  const vec4 D = vec4(0.0, 0.5, 1.0, 2.0);\n"
    "  vec3 i  = floor(v + dot(v, C.yyy));\n"
    "  vec3 x0 = v - i + dot(i, C.xxx);\n"
    "  vec3 g = step(x0.yzx, x0.xyz);\n"
    "  vec3 l = 1.0 - g;\n"
    "  vec3 i1 = min(g.xyz, l.zxy);\n"
    "  vec3 i2 = max(g.xyz, l.zxy);\n"
    "  vec3 x1 = x0 - i1 + C.xxx;\n"
    "  vec3 x2 = x0 - i2 + C.yyy;\n"
    "  vec3 x3 = x0 - D.yyy;\n"
    "  i = mod289(i);\n"
    "  vec4 p = permute( permute( permute(\n"
    "             i.z + vec4(0.0, i1.z, i2.z, 1.0 ))\n"
    "           + i.y + vec4(0.0, i1.y, i2.y, 1.0 ))\n"
    "           + i.x + vec4(0.0, i1.x, i2.x, 1.0 ));\n"
    "  float n_ = 0.142857142857;\n"
    "  vec3 ns = n_ * D.wyz - D.xzx;\n"
    "  vec4 j = p - 49.0 * floor(p * ns.z * ns.z);\n"
    "  vec4 x_ = floor(j * ns.z);\n"
    "  vec4 y_ = floor(j - 7.0 * x_);\n"
    "  vec4 x = x_ * ns.x + ns.yyyy;\n"
    "  vec4 y = y_ * ns.x + ns.yyyy;\n"
    "  vec4 h = 1.0 - abs(x) - abs(y);\n"
    "  vec4 b0 = vec4(x.xy, y.xy);\n"
    "  vec4 b1 = vec4(x.zw, y.zw);\n"
    "  vec4 s0 = floor(b0)*2.0 + 1.0;\n"
    "  vec4 s1 = floor(b1)*2.0 + 1.0;\n"
    "  vec4 sh = -step(h, vec4(0.0));\n"
    "  vec4 a0 = b0.xzyw + s0.xzyw*sh.xxyy;\n"
    "  vec4 a1 = b1.xzyw + s1.xzyw*sh.zzww;\n"
    "  vec3 p0 = vec3(a0.xy, h.x);\n"
    "  vec3 p1 = vec3(a0.zw, h.y);\n"
    "  vec3 p2 = vec3(a1.xy, h.z);\n"
    "  vec3 p3 = vec3(a1.zw, h.w);\n"
    "  vec4 norm = taylorInvSqrt(vec4(dot(p0,p0), dot(p1,p1), dot(p2,p2), dot(p3,p3)));\n"
    "  p0 *= norm.x; p1 *= norm.y; p2 *= norm.z; p3 *= norm.w;\n"
    "  vec4 m = max(0.5 - vec4(dot(x0,x0), dot(x1,x1), dot(x2,x2), dot(x3,x3)), 0.0);\n"
    "  m = m * m;\n"
    "  return 105.0 * dot(m*m, vec4(dot(p0,x0), dot(p1,x1), dot(p2,x2), dot(p3,x3)));\n"
    "}\n"
    "const mat3 rot1 = mat3(-0.37, 0.36, 0.85, -0.14, -0.93, 0.34, 0.92, 0.01, 0.4);\n"
    "const mat3 rot2 = mat3(-0.55, -0.39, 0.74, 0.33, -0.91, -0.24, 0.77, 0.12, 0.63);\n"
    "const mat3 rot3 = mat3(-0.71, 0.52, -0.47, -0.08, -0.72, -0.68, -0.7, -0.45, 0.56);\n"
    "float simplex3d_fractal(vec3 m) {\n"
    "    float result = 0.5333333*simplex3d(m*rot1);\n"
    "    if(complexityL == 2) result += 0.2666667*simplex3d(2.0*m*rot2);\n"
    "    if(complexityL == 3) result += 0.1333333*simplex3d(4.0*m*rot3);\n"
    "    if(complexityL == 4) result += 0.0666667*simplex3d(8.0*m);\n"
    "    return result;\n"
    "}\n"
    "void main(void) {\n"
    "    vec2 out_uvs = texCoord;\n"
    "    vec2 uv = out_uvs;\n"
    "    uv -= vec2(0.5);\n"
    "    uv += vec2(layerOffsetX, layerOffsetY);\n"
    "    uv.x *= scaleX;\n"
    "    uv.y *= scaleY;\n"
    "    uv /= vec2(noiseScale);\n"
    "    uv += vec2(0.5);\n"
    "    uv -= vec2(userOffsetX, userOffsetY);\n"
    "    uv.x *= aspect;\n"
    "    vec3 p3 = vec3(uv, evolution * 0.0015);\n"
    "    float value = simplex3d_fractal(p3*8.0+8.0);\n"
    "    float brightnessMod = (brightness - 0.5) * 0.5;\n"
    "    brightnessMod *= ghettoContrast;\n"
    "    float y = brightnessMod;\n"
    "    float x = ghettoContrast;\n"
    "    value = y + x * value;\n"
    "    value -= (1 - brightness) * 1.0;\n"
    "    value += (brightness * 1.5);\n"
    "    FragColour = max(value, 0.0);\n"
    "    FragColour = min(FragColour, 1.0);\n"
    "}\n";

// ============ Sobel 边缘 ============
static const char* kSobelFS =
    "#version 330\n"
    "uniform sampler2D tex;\n"
    "in vec2 texCoord;\n"
    "out float colourOut;\n"
    "const float sobel1[9] = float[9](1,0,-1,2,0,-2,1,0,-1);\n"
    "const float sobel2[9] = float[9](1,2,1,0,0,0,-1,-2,-1);\n"
    "void main() {\n"
    "    vec2 p = gl_FragCoord.xy - vec2(0.5,0.5);\n"
    "    colourOut = 0.0;\n"
    "    float gx = 0.0; float gy = 0.0;\n"
    "    for (int iy=-1; iy<=1; iy++) {\n"
    "        for (int ix=-1; ix<=1; ix++) {\n"
    "            ivec2 loc = ivec2(p) + ivec2(ix,iy);\n"
    "            loc = clamp(loc, ivec2(0), textureSize(tex,0)-ivec2(1,1));\n"
    "            float val = texelFetch(tex, loc, 0).r;\n"
    "            gx += val * sobel1[(iy+1)*3+(ix+1)];\n"
    "            gy += val * sobel2[(iy+1)*3+(ix+1)];\n"
    "            colourOut = sqrt(gx*gx+gy*gy);\n"
    "        }\n"
    "    }\n"
    "}\n";

// ============ JFA 距离场 (k=0 初始化 + 迭代共用, lastStep 解码) ============
static const char* kJFAFS =
    "#version 330\n"
    "out float frag_color;\n"
    "in vec2 texCoord;\n"
    "uniform sampler2D in_tex;\n"
    "uniform sampler2D jfa_tex;\n"
    "uniform vec2 jfa_res;\n"
    "uniform float alpha_threshold;\n"
    "uniform int k;\n"
    "uniform int lastStepB;\n"
    "uniform int dfModeL;\n"
    "float unit_box_sdf(vec2 p, vec2 c) {\n"
    "    vec2 a = abs(p - c);\n"
    "    return length(max(a, vec2(0.0))) + min(max(a.x, a.y), 0.0);\n"
    "}\n"
    "void main() {\n"
    "    frag_color = uintBitsToFloat(uint(0xffffffff));\n"
    "    vec2 p = gl_FragCoord.xy - vec2(0.5,0.5);\n"
    "    ivec2 c = ivec2(p);\n"
    "    ivec2 inTexSizeL = textureSize(in_tex, 0);\n"
    "    if (k == 0) {\n"
    "        vec2 texture_offset_coords = texCoord;\n"
    "        float alpha = texture(in_tex, texture_offset_coords).r;\n"
    "        if (dfModeL == 1) {\n"
    "            if (alpha <= 1.0 - alpha_threshold) {\n"
    "                uint c_u = (uint(c.x+1) << 16 | uint(c.y+1));\n"
    "                frag_color = uintBitsToFloat(c_u);\n"
    "            } else {\n"
    "                if (c.x == 0 || c.y == 0 || c.x == inTexSizeL.x-1 || c.y == inTexSizeL.y-1) {\n"
    "                    if (c.x == 0) { uint c_u = (uint(c.x) << 16 | uint(c.y+1)); frag_color = uintBitsToFloat(c_u); }\n"
    "                    if (c.y == 0) { uint c_u = (uint(c.x+1) << 16 | uint(c.y)); frag_color = uintBitsToFloat(c_u); }\n"
    "                    if (c.x == inTexSizeL.x-1) { uint c_u = (uint(c.x+2) << 16 | uint(c.y+1)); frag_color = uintBitsToFloat(c_u); }\n"
    "                    if (c.y == inTexSizeL.y-1) { uint c_u = (uint(c.x+1) << 16 | uint(c.y+2)); frag_color = uintBitsToFloat(c_u); }\n"
    "                }\n"
    "            }\n"
    "        } else if (dfModeL == 2) {\n"
    "            float v = abs(alpha);\n"
    "            v = clamp(v, 0.0, 1.0);\n"
    "            if (v < alpha_threshold) {\n"
    "                if (c.x == 0 || c.y == 0 || c.x == inTexSizeL.x-1 || c.y == inTexSizeL.y-1) {\n"
    "                    if (c.x == 0) { uint c_u = (uint(c.x) << 16 | uint(c.y+1)); frag_color = uintBitsToFloat(c_u); }\n"
    "                    if (c.y == 0) { uint c_u = (uint(c.x+1) << 16 | uint(c.y)); frag_color = uintBitsToFloat(c_u); }\n"
    "                    if (c.x == inTexSizeL.x-1) { uint c_u = (uint(c.x+2) << 16 | uint(c.y+1)); frag_color = uintBitsToFloat(c_u); }\n"
    "                    if (c.y == inTexSizeL.y-1) { uint c_u = (uint(c.x+1) << 16 | uint(c.y+2)); frag_color = uintBitsToFloat(c_u); }\n"
    "                }\n"
    "            } else {\n"
    "                uint c_u = (uint(c.x+1) << 16 | uint(c.y+1));\n"
    "                frag_color = uintBitsToFloat(c_u);\n"
    "            }\n"
    "        }\n"
    "        return;\n"
    "    }\n"
    "    float best = 1e30;\n"
    "    for (int i = -1; i <= 1; i += 1) {\n"
    "        for (int j = -1; j <= 1; j += 1) {\n"
    "            ivec2 s = c + ivec2(i*k, j*k);\n"
    "            if (any(lessThan(ivec4(s, jfa_res - 1), ivec4(0, 0, s)))) continue;\n"
    "            uint c_u = floatBitsToUint(texelFetch(jfa_tex, s, 0).r);\n"
    "            if (c_u == uint(0xffffffff)) continue;\n"
    "            vec2 q = vec2(uint(c_u >> 16), uint(c_u & uint(0x0000ffff))) - vec2(1,1);\n"
    "            float d = unit_box_sdf(p, q);\n"
    "            if (d < best) { best = d; frag_color = uintBitsToFloat(c_u); }\n"
    "        }\n"
    "    }\n"
    "    if (lastStepB == 1) {\n"
    "        uint c_u = floatBitsToUint(frag_color);\n"
    "        vec2 q = vec2(uint(c_u >> 16), uint(c_u & uint(0x0000ffff))) - vec2(1,1);\n"
    "        float dist = distance(p, q);\n"
    "        frag_color = dist;\n"
    "    }\n"
    "}\n";

// ============ 图层合成 (预设引擎 GPU 版) ============
// 语义与 CPU renderPreset 一致 (设计 填充效果):
//   distTex.r = 到种子点的归一化传播距离 (0=种子点, 1=最远), 由 CPU 计算
//   progress = 播放进度 0-100
//   fillMap = 覆盖率场 = 1 - smoothstep(radius-SOFT, radius+SOFT, nd)
//   层窗口 = fillMap 覆盖率区间 [start/100, end/100] 带通 (波前扫过环带)
static const char* kLayersFS =
    "#version 330\n"
    "uniform sampler2D distTex;\n"
    "uniform sampler2D noiseTex;\n"
    "uniform sampler2D srcTex;\n"
    "uniform sampler2D edgeTex;\n"
    "uniform float progress;\n"
    "uniform float softEdge;\n"
    "uniform int speedMapChannel;\n"
    "uniform float speedMapInfluenceF;\n"
    "uniform float borderInfluenceF;\n"
    "uniform float gammaF;\n"
    "uniform float exposureF;\n"
    "uniform int nLayers;\n"
    "uniform int dbgLayer;\n"
    "uniform float L_start[5];\n"
    "uniform float L_end[5];\n"
    "uniform int L_mode[5];\n"
    "uniform vec4 L_color[5];\n"
    "uniform int L_nStops[5];\n"
    "uniform vec4 L_stops[60];\n"
    "uniform float L_stopsA[60];\n"
    "uniform float L_grow[5];\n"
    "uniform int L_overlay[5];\n"
    "uniform float L_opacity[5];\n"
    "uniform float L_blur[5];\n"
    "uniform float L_displace[5];\n"
    "uniform float L_displaceSize[5];\n"
    "uniform int L_gradientMode[5];\n"
    "uniform vec2 texelSize;\n"
    "in vec2 texCoord;\n"
    "out vec4 colourOut;\n"
    "float smoothstepF(float e0, float e1, float x) {\n"
    "    float t = clamp((x - e0) / (e1 - e0), 0.0, 1.0);\n"
    "    return t * t * (3.0 - 2.0 * t);\n"
    "}\n"
    "float overlayS(float bg, float fg) {\n"
    "    return bg < 0.5 ? (2.0 * bg * fg) : (1.0 - 2.0 * (1.0 - bg) * (1.0 - fg));\n"
    "}\n"
    "vec4 sampleGradient(int layer, float pos) {\n"
    "    int n = L_nStops[layer];\n"
    "    if (n <= 0) return L_color[layer];\n"
    "    pos = clamp(pos, 0.0, 1.0);\n"
    "    int base = layer * 12;\n"
    "    if (pos <= L_stops[base].a) return vec4(L_stops[base].rgb, L_stopsA[base]);\n"
    "    for (int i = 1; i < 12; i++) {\n"
    "        if (i >= n) break;\n"
    "        vec4 s0 = L_stops[base+i-1];\n"
    "        vec4 s1 = L_stops[base+i];\n"
    "        if (pos <= s1.a) {\n"
    "            float span = s1.a - s0.a;\n"
    "            float f = span > 0.0 ? (pos - s0.a) / span : 0.0;\n"
    "            float a0 = L_stopsA[base+i-1];\n"
    "            float a1 = L_stopsA[base+i];\n"
    "            return vec4(mix(s0.rgb, s1.rgb, f), mix(a0, a1, f));\n"
    "        }\n"
    "    }\n"
    "    int last = base + n - 1;\n"
    "    return vec4(L_stops[last].rgb, L_stopsA[last]);\n"
    "}\n"
    "vec3 blendRGB(vec3 dst, vec3 src, int mode) {\n"
    "    // 仅保留有实现依据的混合 (shader 仅 3 种):\n"
    "    //   3=Multiply ( prev*cur), 6=Add ( v0+v1), 9=Overlay ()\n"
    "    //   其余 (7/10/12/14/15/16/17) 无实现依据 — src-over 直接叠加\n"
    "    if (mode == 3) return dst * src;\n"
    "    if (mode == 6) return clamp(dst + src, 0.0, 1.0);\n"
    "    if (mode == 9) return mix(2.0*dst*src, 1.0-2.0*(1.0-dst)*(1.0-src), step(0.5, dst));\n"
    "    return clamp(src, 0.0, 1.0);\n"
    "}\n"
    "vec3 clampRGB(vec3 c) { return clamp(c, 0.0, 1.0); }\n"
    "void main() {\n"
    "    vec4 dst = vec4(0.0);\n"
    "    // 传播距离场: 0=种子点, 1=最远 (CPU 计算传入); 形状外=2.0 标记\n"
    "    float raw = texture(distTex, texCoord).r;\n"
    "    float outside = step(1.001, raw);   // 1=形状外: 永不填充\n"
    "    float nd = clamp(raw, 0.0, 1.0);\n"
    "    // fillMap 覆盖率场: 波前半径 = progress/100\n"
    "    float radius = clamp(progress, 0.0, 100.0) * 0.01;\n"
    "    // fillMap 覆盖率场: nd<=p01 已填充, 波前边缘平滑 (softEdge=1px, 设计 coverage 子像素)\n"
    "    float fill = 1.0 - smoothstepF(radius, radius + softEdge, nd);\n"
    "    fill = clamp(fill, 0.0, 1.0) * (1.0 - outside);\n"
    "    // Fill_GPU (设计 ): speedOverlay(fill, 速度图) + borderControl(边缘) + gamma\n"
    "    {\n"
    "        // 速度图: 距离场 (channel<0) 或源图像素通道 (0=Luma 1=R 2=G 3=B 4=A,\n"
    "        // 设计  内核 + 面板 Channel 参数)\n"
    "        float spd;\n"
    "        if (speedMapChannel < 0) {\n"
    "            spd = nd;\n"
    "        } else {\n"
    "            vec4 srcp = texture(srcTex, texCoord);\n"
    "            if (speedMapChannel == 0) spd = 0.299*srcp.r + 0.587*srcp.g + 0.114*srcp.b;\n"
    "            else if (speedMapChannel == 1) spd = srcp.r;\n"
    "            else if (speedMapChannel == 2) spd = srcp.g;\n"
    "            else if (speedMapChannel == 3) spd = srcp.b;\n"
    "            else spd = srcp.a;\n"
    "            if (spd < 0.001) spd = 0.0;   // 阈值 \n"
    "            spd = clamp(spd, 0.0, 1.0);\n"
    "        }\n"
    "        float ov = overlayS(fill, spd);\n"
    "        fill = ov * speedMapInfluenceF + fill * (1.0 - speedMapInfluenceF);\n"
    "        fill = clamp(fill, 0.0, 1.0) * (1.0 - outside);\n"
    "        float bv = texture(edgeTex, texCoord).r;  // border = Sobel 边缘\n"
    "        fill = bv * fill * borderInfluenceF + fill * (1.0 - borderInfluenceF);\n"
    "        fill = clamp(fill, 0.0, 1.0) * (1.0 - outside);\n"
    "        if (fill < 1.0e-4) fill = 0.0;\n"
    "        fill = pow(fill, gammaF) * exposureF;\n"
    "        fill = clamp(fill, 0.0, 1.0) * (1.0 - outside);\n"
    "    }\n"
    "    float p01 = clamp(progress, 0.0, 100.0) * 0.01;\n"
    "    for (int li = 0; li < 5; li++) {\n"
    "        if (li >= nLayers) break;\n"
    "        // 层窗口: 传播进度区间带通 × 已填充区 (波前扫过时各层依次显现)\n"
    "        // 上沿从 hi 淡出 (100%% 时完全打开)\n"
    "        float lo = min(L_start[li], L_end[li]) * 0.01;\n"
    "        float hi = max(L_start[li], L_end[li]) * 0.01;\n"
    "        const float WB = 0.03;\n"
    "        float win = smoothstepF(lo - WB, lo + WB, p01) *\n"
    "                    (1.0 - smoothstepF(hi, hi + WB, p01));\n"
    "        // grow: 线性调制推进 (无 pow 依据; 设计为线性缩放+膨胀核)\n"
    "        float g = L_grow[li];\n"
    "        float fillG = fill;\n"
    "        if (g != 0.0 && fillG > 0.001) {\n"
    "            float ndA = clamp(nd - g * 0.01, 0.0, 1.0);\n"
    "            fillG = clamp(1.0 - smoothstepF(p01, p01 + softEdge, ndA), 0.0, 1.0);\n"
    "            if (fill <= 0.001) fillG = 0.0;\n"
    "        }\n"
    "        // blur: 对填充场高斯模糊 (设计 / 输入=fillMap;\n"
    "        // 模糊外扩到未填充区=柔光; 形状外 (outside) 自然为 0)\n"
    "        if (L_blur[li] > 0.5) {\n"
    "            float br = L_blur[li] * 0.1;\n"
    "            int r1 = int(floor(br));\n"
    "            int r2 = r1 + 1;\n"
    "            float al = br - float(r1);\n"
    "            float acc1 = 0.0, acc2 = 0.0, tw1 = 0.0, tw2 = 0.0;\n"
    "            for (int oy = -2; oy <= 2; oy++) {\n"
    "                for (int ox = -2; ox <= 2; ox++) {\n"
    "                    vec2 off = vec2(float(ox), float(oy)) * br * texelSize;\n"
    "                    float nraw = texture(distTex, texCoord + off).r;\n"
    "                    float nout = step(1.001, nraw);\n"
    "                    float nnd = clamp(nraw, 0.0, 1.0);\n"
    "                    float nf = 1.0 - smoothstepF(radius, radius + softEdge, nnd);\n"
    "                    nf = clamp(nf, 0.0, 1.0) * (1.0 - nout);\n"
    "                    if (g != 0.0 && nf > 0.001) {\n"
    "                        float nndA = clamp(nnd - g * 0.01, 0.0, 1.0);\n"
    "                        nf = clamp(1.0 - smoothstepF(p01, p01 + softEdge, nndA), 0.0, 1.0);\n"
    "                        if (nf <= 0.001) nf = 0.0;\n"
    "                    }\n"
    "                    // 可分离高斯权重 w(ox)*w(oy), r=2 归一化 (5-tap 截断)\n"
    "                    float wx1 = exp(-0.5 * float(ox)*float(ox) / 4.0 / 0.06);\n"
    "                    float wy1 = exp(-0.5 * float(oy)*float(oy) / 4.0 / 0.06);\n"
    "                    float w1 = wx1 * wy1;\n"
    "                    acc1 += w1 * nf; tw1 += w1;\n"
    "                    float invR2 = 1.0 / float(max(r2, 1));\n"
    "                    float wx2 = exp(-0.5 * float(ox)*float(ox) * invR2 * invR2 / 0.06);\n"
    "                    float wy2 = exp(-0.5 * float(oy)*float(oy) * invR2 * invR2 / 0.06);\n"
    "                    float w2 = wx2 * wy2;\n"
    "                    acc2 += w2 * nf; tw2 += w2;\n"
    "                }\n"
    "            }\n"
    "            float b1 = tw1 > 0.0 ? acc1 / tw1 : 0.0;\n"
    "            float b2 = tw2 > 0.0 ? acc2 / tw2 : 0.0;\n"
    "            fillG = mix(b1, b2, al) * (1.0 - outside);\n"
    "        }\n"
    "        float wA = win * fillG;\n"
    "        if (wA <= 0.001) continue;\n"
    "        // 波前位置 (渐变取色; grow 只影响推进不影响取色)\n"
    "        float w = nd;\n"
    "        // displace: 采样坐标置换 (设计 : 四边形扭曲采样; Noise_X/Y_Displacement)\n"
    "        // 噪声位移后坐标重新采样距离场/填充场 — 扭曲填充与取色\n"
    "        if (L_displaceSize[li] > 0.0 && L_displace[li] > 0.0) {\n"
    "            float nv = texture(noiseTex, texCoord).r;\n"
    "            float off = (nv - 0.5) * 2.0 * L_displace[li] * 0.01 * (L_displaceSize[li] * 0.01);\n"
    "            vec2 dispUV = texCoord + vec2(off, off);\n"
    "            float draw = texture(distTex, dispUV).r;\n"
    "            float dout = step(1.001, draw);\n"
    "            float dnd = clamp(draw, 0.0, 1.0);\n"
    "            float df = 1.0 - smoothstepF(radius, radius + softEdge, dnd);\n"
    "            df = clamp(df, 0.0, 1.0) * (1.0 - dout);\n"
    "            // grow 调制 (与 fillG 相同逻辑)\n"
    "            if (g != 0.0 && df > 0.001) {\n"
    "                float dndA = clamp(dnd - g * 0.01, 0.0, 1.0);\n"
    "                df = clamp(1.0 - smoothstepF(p01, p01 + softEdge, dndA), 0.0, 1.0);\n"
    "                if (df <= 0.001) df = 0.0;\n"
    "            }\n"
    "            // blur 近似: 采样已 blur 的填充场不可得, 用 fillG 与 df 的折中 (近似)\n"
    "            wA = win * mix(fillG, df, 0.5);\n"
    "            if (wA <= 0.001) continue;\n"
    "            w = dnd;\n"
    "        }\n"
    "        vec4 col;\n"
    "        // mode: 1=实色 2=渐变 3=原图; 0=设计无 mode 字段(有 stops 即渐变)\n"
    "        if (L_mode[li] == 1) col = L_color[li];\n"
    "        else if (L_mode[li] == 2 || (L_mode[li] == 0 && L_nStops[li] > 0)) {\n"
    "            float pos = w;\n"
    "            if (L_gradientMode[li] == 2) {\n"
    "                float span = (hi - lo);\n"
    "                pos = span > 0.0 ? clamp((p01 - lo) / span, 0.0, 1.0) : 0.0;\n"
    "            }\n"
    "            col = sampleGradient(li, pos);\n"
    "        }\n"
    "        else if (L_mode[li] == 3) col = texture(srcTex, texCoord);\n"
    "        else col = L_color[li];\n"
    "        float op = clamp(L_opacity[li], 0.0, 100.0) * 0.01;\n"
    "        // 颜色 alpha 参与层权重: 渐变末端透明黑不能覆盖原图\n"
    "        float outA = wA * op * col.a;\n"
    "        if (dbgLayer == li + 1) { colourOut = vec4(col.r, col.g, col.b, col.a); return; } /* DBG col */\n"
    "        vec3 br;\n"
    "        if (dst.a <= 0.001 && dst.r <= 0.001 && dst.g <= 0.001 && dst.b <= 0.001)\n"
    "            br = clampRGB(col.rgb); // src-over: 透明黑底直接用源色\n"
    "        else br = clampRGB(blendRGB(dst.rgb, col.rgb, L_overlay[li]));\n"
    "        dst.rgb = dst.rgb + (br - dst.rgb) * outA;\n"
    "        dst.a = dst.a + outA * (1.0 - dst.a);\n"
    "    }\n"
    "    colourOut = dst;\n"
    "}\n";

